version: '3.8'
services:
  server:
    image: ghcr.io/wg-easy/wg-easy:latest
    environment:
      - WG_HOST=192.168.3.114
      - PASSWORD_HASH=$$2a$$12$$Hv//SyNgN5DKAWBoXnm3Cecy2NO3oA9UsIRwJEAVzN3HbTL/MsLA6
      - PORT=51821
      - WG_PORT=51820
    volumes:
      - ./wg-easy:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
  server-raw:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./wg:/etc/wireguard/
    cap_add:
      - NET_ADMIN             # Required for WireGuard, give container network admin privileges
      - SYS_MODULE            # Required for WireGuard, give container access to kernel modules
    devices:
      - /dev/net/tun          # Required for WireGuard, give container access to TUN device
    sysctls:
      - net.ipv4.ip_forward=1 # Required for WireGuard, enable IP forwarding
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - 51830:51830/udp
    command: ["tail", "-f", "/dev/null"]
  wg-10.8.1.2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./wg-10.8.1.2:/etc/wireguard/
    cap_add:
      - NET_ADMIN             # Required for WireGuard, give container network admin privileges
      - SYS_MODULE            # Required for WireGuard, give container access to kernel modules
    devices:
      - /dev/net/tun          # Required for WireGuard, give container access to TUN device
    sysctls:
      - net.ipv4.ip_forward=1 # Required for WireGuard, enable IP forwarding
      - net.ipv4.conf.all.src_valid_mark=1
    command: ["tail", "-f", "/dev/null"]
