version: '3.8'
services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./wg0.conf:/etc/wireguard/wg0.conf
  #   cap_add:
  #     - NET_ADMIN             # Required for WireGuard, give container network admin privileges
  #     - SYS_MODULE            # Required for WireGuard, give container access to kernel modules
  #   devices:
  #     - /dev/net/tun          # Required for WireGuard, give container access to TUN device
  #   sysctls:
  #     - net.ipv4.ip_forward=1 # Required for WireGuard, enable IP forwarding
  #   command: ["tail", "-f", "/dev/null"]
  #   # command: ["wg-quick", "up", "wg0"]
  # client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./wg0-client.conf:/etc/wireguard/wg0-client.conf
  #   cap_add:
  #     - NET_ADMIN             # Required for WireGuard, give container network admin privileges
  #     - SYS_MODULE            # Required for WireGuard, give container access to kernel modules
  #   devices:
  #     - /dev/net/tun          # Required for WireGuard, give container access to TUN device
  #   sysctls:
  #     - net.ipv4.ip_forward=1 # Required for WireGuard, enable IP forwarding
  #   command: ["tail", "-f", "/dev/null"]
  #   # command: ["wg-quick", "up", "wg0-client"]

  # docker run -d \
  # --name=wg-easy \
  # -e LANG=de \
  # -e WG_HOST=<🚨YOUR_SERVER_IP> \
  # -e PASSWORD_HASH=<🚨YOUR_ADMIN_PASSWORD_HASH> \
  # -e PORT=51821 \
  # -e WG_PORT=51820 \
  # -v ~/.wg-easy:/etc/wireguard \
  # -p 51820:51820/udp \
  # -p 51821:51821/tcp \
  # --cap-add=NET_ADMIN \
  # --cap-add=SYS_MODULE \
  # --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  # --sysctl="net.ipv4.ip_forward=1" \
  # --restart unless-stopped \
  # ghcr.io/wg-easy/wg-easy
  server:
    image: ghcr.io/wg-easy/wg-easy:latest
    environment:
      - WG_HOST=223.255.165.246
      - PASSWORD_HASH=$$2a$$12$$Hv//SyNgN5DKAWBoXnm3Cecy2NO3oA9UsIRwJEAVzN3HbTL/MsLA6
      - PORT=51821
      - WG_PORT=51820
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
  client:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./wg-easy-0.conf:/etc/wireguard/wg-easy-0.conf
    cap_add:
      - NET_ADMIN             # Required for WireGuard, give container network admin privileges
      - SYS_MODULE            # Required for WireGuard, give container access to kernel modules
    devices:
      - /dev/net/tun          # Required for WireGuard, give container access to TUN device
    sysctls:
      - net.ipv4.ip_forward=1 # Required for WireGuard, enable IP forwarding
      - net.ipv4.conf.all.src_valid_mark=1
    command: ["tail", "-f", "/dev/null"]
    # command: ["wg-quick", "up", "wg0-client"]

